### ISSUE TITLE
上传主题报错Internal Server Error: The [theme.yaml] does not conform to the theme specification.

### ISSUE THREAD

**Issue by NiuXiaoGuang** [7Wate/Redemption#1]
我Halo版本是2.2版的

**Comment by 7wate** [comment]
主题目前还未适配 Halo 2.0 以上版本，我会尽快更新适配的 ~

**Comment by 7wate** [comment]
简单了解 Halo >=2.0.0 版本，弃用了 FreeMarker 引擎，采用了 Thymeleaf 引擎。适配的话需要项目推到重来，目前暂时没有太多空闲时间，很抱歉哈 😁
